### ISSUE TITLE
The vpnOutput.write case a issue : "no buffer space available",do you know why?

### ISSUE THREAD

**Issue by gongquanlin** [axnamit/androidFirewallUsingVpnService#1]
When I start the vpn and test it's speed,the services throw an error.
no buffer space available
do you know why?

**Comment by axnamit** [comment]
please share screen shoot of the issue

**Comment by gongquanlin** [comment]
I solved it，thanks.Bytebuffer I set is too large to lead the issue

**Comment by axnamit** [comment]
thanks ! i will do the same
